In [7]:
# 1.Crie um array com os números de 0 a 9, utilize somente 1 dimensão.

import numpy
array = numpy.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# 2.Crie um array com os números de 0 a 9 como o exercício anterior, 
# mas utilize List Compreensions.

import numpy
array = numpy.array([i for i in range(0,10)])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 3.Crie um array com os números de 0 a 8, utilize 2 dimensões, ou seja, 
# com 3 linhas (3x3)

import numpy
array = numpy.arange(9).reshape((3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# 4.Crie um array do tipo float, com 10 número de sua escolha, 
# mas utilize 32 bits/4 bytes.

import numpy
array = numpy.arange(0,9, dtype='f4')
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [11]:
# 5.Crie um array com os números de 1 a 20, escolhendo o tipo de dado que 
# ocupara o menor espaço da memoria. Em seguida imprima o quanto 
# ele ocupou em bytes.

import numpy
array = numpy.arange(1,21, dtype=numpy.int8)
print(array)
print(array.nbytes)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20


In [12]:
# 6.Crie uma matriz 2x2 e imprima o primeiro elemento da primeira linha, 
# e o último elemento da última linha.

import numpy
array = numpy.random.randint(1,5,(2,2))
print(array)
print(array[0,0])
print(array[1,1])

[[3 2]
 [2 3]]
3
3


In [13]:
# 7.Gere uma array 3x3 com números inteiros aleatórios entre 5 e 20. 
# Então imprima a primeira coluna e última linha

import numpy
array = numpy.random.randint(5,20,(3,3))
print(array)
print(array[:,0])
print(array[2,:])



[[17 15  7]
 [16 11  6]
 [14  7 18]]
[17 16 14]
[14  7 18]


In [14]:
# 8. Crie uma matriz 3x3 aleatória. Percorra linha por linha com um laço e 
# imprima a soma de cada linha.

import numpy
array = numpy.random.randint(1,50,(3,3))
print(array)
for linha in array:
  print(numpy.sum(linha))



[[15 15  8]
 [39 28 14]
 [ 3 22 43]]
38
81
68


In [15]:
# 9.Gere um array com os valores pares de 0 a 100 com list comprehension.

import numpy
array = numpy.array([i for i in range(0,101) if i % 2 ==0 ])
print(array)



[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [16]:
# 10.Crie uma array 4x9 com valores quaisquer, redimensione para as 
# dimensões 36, e 6x6

import numpy
array = numpy.random.randint(0,10,(4,9))
print(array.reshape((36)))
print(array.reshape((6,6)))



[5 6 5 8 2 0 4 5 5 5 2 0 1 9 4 7 2 3 8 8 8 8 6 2 8 2 5 0 1 1 4 6 3 2 9 6]
[[5 6 5 8 2 0]
 [4 5 5 5 2 0]
 [1 9 4 7 2 3]
 [8 8 8 8 6 2]
 [8 2 5 0 1 1]
 [4 6 3 2 9 6]]


In [17]:
# 11. Crie uma função que receba três arrays de mesmo formato, então retorne 
# elas concatenadas em uma só. Se as matrizes recebidas não forem do 
# mesmo formato gere uma exceção.

import numpy

def combina(arr1,arr2,arr3):
  if arr1.shape != arr2.shape or arr1.shape != arr3.shape:
    raise Exception("Formatos são diferentes")
  
  return numpy.concatenate((arr1,arr2,arr3))

array1 = numpy.array([1,2,3])
array2 = numpy.array([4,5,6])
array3 = numpy.array([7,8,9])

print(combina(array1,array2,array3))



[1 2 3 4 5 6 7 8 9]


In [18]:
# 12.Crie uma função que divida um array em N pedaços, mas mantenha so os 
# valores absolutos dos valores deste array.

import numpy
def divide_abs(arr,n):
  arr = numpy.array_split(arr,n)
  arr = numpy.abs(arr)
  return arr

array1 = numpy.array([1,2,3,-4,5,-7])
print(divide_abs(array1,2))



[[1 2 3]
 [4 5 7]]


In [19]:
# 13.Crie uma função que receba um array e retorne quantos números positivos ela 
# contêm.

import numpy

def conta_positivos(arr):
  return len(numpy.where(arr>0)[0])

array = numpy.array([1,2,3,4,5,-7])
print(conta_positivos(array))



5


In [20]:
#14.Crie uma função que receba uma matriz e retorne os índices dos números que 
# são divisíveis por 3.

import numpy

def divisiveis_por_3(arr):
  return numpy.where(arr % 3 == 0)[0]

array = numpy.array([4,5,6,7,8,9])
print(divisiveis_por_3(array))



[2 5]


In [21]:
# 15.Crie uma função que diga se um array possui números negativos

import numpy

def tem_negativo(arr):
  return numpy.any(arr <0)

array = numpy.array([4,-5,6,7,8])
print(tem_negativo(array))



True


In [22]:
# 16.Crie uma função que remova os números negativos de uma array.

import numpy
def tira_negativo(arr):
  filter = arr >=0
  return arr[filter]

array = numpy.array([1,-5,5,4,3,-2,-1])
print(tira_negativo(array))



[1 5 4 3]


In [23]:
# 17.Crie uma função que receba um número inicial e final, e uma array. 
# A função deve retornar uma nova array somente com os números 
# dentro deste intervalo.

import numpy

def remove_valores(arr, inicial, final):
  filter = (arr >= inicial) & (arr <= final)
  return arr[filter]

array = numpy.array([i for i in range(-10,11)])
print(array)
print(remove_valores(array,0,7))



[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
[0 1 2 3 4 5 6 7]


In [24]:
# 18.Crie uma função que ordene uma matriz e remova todos os números impares.

import numpy

def ordena_pares(arr):
  arr = numpy.sort(arr)
  filter = arr % 2 == 1
  return arr[filter]

array = numpy.random.randint(0,10,(100))  
print(ordena_pares(array))




[1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 5 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]


In [25]:
# 19.Realize o mesmo exercício anterior, mas remova valores duplicados.

import numpy

def ordena_pares_unicos(arr):
  arr = numpy.sort(arr)
  filter = arr % 2 == 1
  return numpy.unique( arr[filter])

array = numpy.random.randint(0,10,(100))  
print(ordena_pares_unicos(array))


[1 3 5 7 9]
